export * from './robinsonService.js';
export {
  callService,
  adminLogin,
  getToken,
  getAssemblyId,
  setAssemblyContext,
  fetchAssemblyMetadata,
  fetchAttendanceList,
  fetchQuestionList,
  fetchVotingScrutiny,
  fetchVotingResults,
  fetchAssemblyStatus,
  fetchQuorumSnapshot,
  fetchAdminInfo,
  fetchActiveAssemblies,
  mapAttendance,
  mapVotingResults,
  mapVotingDetail,
  mapQuorum,
  mapQuorumSnapshot,
} from './adapters/tecnoreunionesAdapter.js';

export {
  queryTecnoreuniones,
  dbFetchQuestions,
  dbFetchAssemblyStatus,
  dbFetchAttendanceList,
  dbFetchVotingResults,
  dbFetchQuorumSnapshot,
  dbFetchAssemblyMetadata,
  dbFetchVotingScrutiny,
  dbFetchLastAnsweredQuestion,
  dbListTables,
  dbDescribeTable,
  closePool,
} from './adapters/tecnoreunionesDb.js';
